# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rgateway.proto\x12\x07gateway"_\n\x13OptimizationRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x17\n\x0fmodel_requested\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0e\n\x06org_id\x18\x04 \x01(\t"w\n\x14OptimizationResponse\x12\x18\n\x10optimized_prompt\x18\x01 \x01(\t\x12\x14\n\x0ctarget_model\x18\x02 \x01(\t\x12\x16\n\x0eshould_use_oss\x18\x03 \x01(\x08\x12\x17\n\x0f\x63\x61\x63hed_response\x18\x04 \x01(\t";\n\x12\x43\x61\x63heUpdateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x15\n\rresponse_json\x18\x02 \x01(\t"&\n\x13\x43\x61\x63heUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xa8\x01\n\tOptimizer\x12O\n\x0eOptimizePrompt\x12\x1c.gateway.OptimizationRequest\x1a\x1d.gateway.OptimizationResponse"\x00\x12J\n\x0bUpdateCache\x12\x1b.gateway.CacheUpdateRequest\x1a\x1c.gateway.CacheUpdateResponse"\x00\x42\x31Z/github.com/abhinavtyagiO/ai-gateway-proxy/protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "gateway_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals["DESCRIPTOR"]._options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z/github.com/abhinavtyagiO/ai-gateway-proxy/proto"
    )
    _globals["_OPTIMIZATIONREQUEST"]._serialized_start = 26
    _globals["_OPTIMIZATIONREQUEST"]._serialized_end = 121
    _globals["_OPTIMIZATIONRESPONSE"]._serialized_start = 123
    _globals["_OPTIMIZATIONRESPONSE"]._serialized_end = 242
    _globals["_CACHEUPDATEREQUEST"]._serialized_start = 244
    _globals["_CACHEUPDATEREQUEST"]._serialized_end = 303
    _globals["_CACHEUPDATERESPONSE"]._serialized_start = 305
    _globals["_CACHEUPDATERESPONSE"]._serialized_end = 343
    _globals["_OPTIMIZER"]._serialized_start = 346
    _globals["_OPTIMIZER"]._serialized_end = 514
# @@protoc_insertion_point(module_scope)
