# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gateway_pb2 as gateway__pb2


class OptimizerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OptimizePrompt = channel.unary_unary(
            "/gateway.Optimizer/OptimizePrompt",
            request_serializer=gateway__pb2.OptimizationRequest.SerializeToString,
            response_deserializer=gateway__pb2.OptimizationResponse.FromString,
        )
        self.UpdateCache = channel.unary_unary(
            "/gateway.Optimizer/UpdateCache",
            request_serializer=gateway__pb2.CacheUpdateRequest.SerializeToString,
            response_deserializer=gateway__pb2.CacheUpdateResponse.FromString,
        )


class OptimizerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def OptimizePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_OptimizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "OptimizePrompt": grpc.unary_unary_rpc_method_handler(
            servicer.OptimizePrompt,
            request_deserializer=gateway__pb2.OptimizationRequest.FromString,
            response_serializer=gateway__pb2.OptimizationResponse.SerializeToString,
        ),
        "UpdateCache": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateCache,
            request_deserializer=gateway__pb2.CacheUpdateRequest.FromString,
            response_serializer=gateway__pb2.CacheUpdateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "gateway.Optimizer", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Optimizer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OptimizePrompt(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gateway.Optimizer/OptimizePrompt",
            gateway__pb2.OptimizationRequest.SerializeToString,
            gateway__pb2.OptimizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def UpdateCache(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/gateway.Optimizer/UpdateCache",
            gateway__pb2.CacheUpdateRequest.SerializeToString,
            gateway__pb2.CacheUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
