# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gateway.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "gateway.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rgateway.proto\x12\x07gateway"_\n\x13OptimizationRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x17\n\x0fmodel_requested\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0e\n\x06org_id\x18\x04 \x01(\t"^\n\x14OptimizationResponse\x12\x18\n\x10optimized_prompt\x18\x01 \x01(\t\x12\x14\n\x0ctarget_model\x18\x02 \x01(\t\x12\x16\n\x0eshould_use_oss\x18\x03 \x01(\x08\x32\\\n\tOptimizer\x12O\n\x0eOptimizePrompt\x12\x1c.gateway.OptimizationRequest\x1a\x1d.gateway.OptimizationResponse"\x00\x42\x31Z/github.com/abhinavtyagiO/ai-gateway-proxy/protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "gateway_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z/github.com/abhinavtyagiO/ai-gateway-proxy/proto"
    )
    _globals["_OPTIMIZATIONREQUEST"]._serialized_start = 26
    _globals["_OPTIMIZATIONREQUEST"]._serialized_end = 121
    _globals["_OPTIMIZATIONRESPONSE"]._serialized_start = 123
    _globals["_OPTIMIZATIONRESPONSE"]._serialized_end = 217
    _globals["_OPTIMIZER"]._serialized_start = 219
    _globals["_OPTIMIZER"]._serialized_end = 311
# @@protoc_insertion_point(module_scope)
